### ISSUE TITLE
Create Components for @codelab/ui

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#1]
Create a new PR after each component has been completed. Add the PR number next to the task like so.

- [x] Example #2

Additionally for each component, write a unit test to ensure that it rendered. Import the default storybook component so you don't have to recreate the component & data.

https://github.com/codelab-ai/codelab.ai/blob/e2403434642fbc3763a089ef34573f6c35af6e14/libs/ui/src/components/button/Button.spec.tsx#L3

There are many ways to test the components, and would be different for each. Fallback to using test-id if you can't think of testing any other way.

1) test for role/label/text or some other method
2) test for test-id

We are just doing a single simple jest test for each component to make sure it rendered correctly. In the future we can test for actual features if needed.

https://github.com/codelab-ai/codelab.ai/blob/e2403434642fbc3763a089ef34573f6c35af6e14/libs/ui/src/components/button/Button.spec.tsx#L5-L11

---
- [x] Button
- [x] Icon #23 
- [x] Typography #24 
- [x] Divider #26 
- [x] Grid
- [x] Layout
- [x] Space
- [x] Affix #40 
- [x] Breadcrumb
- [x] Dropdown * #21 
- [x] Menu 
- [x] Pagination
- [x] PageHeader #43 
- [x] Steps
- [x] AutoComplete
- [x] Checkbox * #14 
- [x] Casader
- [x] DatePicker
- [x] Form ** #12  
- [x] InputNumber
- [x] Input * #13 
- [x] Mentions
- [x] Rate #29 
- [x] Radio #27 
- [x] Switch #28 
- [x] Slider (k)
- [x] Select * #15 
- [x] TreeSelect
- [x] Transfer
- [x] TimePicker
- [x] Upload
- [x] Avatar
- [x] Badge
- [x] Comment
- [x] Collapse
- [x] Carousel
- [x] Card
- [x] Calendar
- [x] Descriptions
- [x] Empty #42 
- [x] List
- [x] Popover
- [x] Statistic
- [x] Tree
- [x] Tooltip #44 
- [x] Timeline #45 
- [x] Tag #41 
- [x] Tabs
- [x] Table
- [x] Alert #25 
- [x] Drawer
- [x] Modal
- [x] Message
- [x] Notification
- [x] Progress
- [x] Popconfirm
- [x] Result
- [x] Spin
- [x] Skeleton
- [x] Anchor
- [x] BackTop
- [x] ConfigProvider

**Comment by webberwang** [comment]
nice work all done!

**Comment by VienNguyen24hdev** [comment]
via Hubstaff
User: Nguyen Luong Vien

Project: Codelab - https://app.hubstaff.com/projects/1093588
Date Range: 09/10/20 - 09/14/20
Work session total: 5:01:21
Billable: Yes

Grand total: 5:01:21
