### ISSUE TITLE
RTM Workflow for Props Module

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#100]
## Overview

https://www.opencodez.com/software-testing/create-requirement-traceability-matrix-rtm-free-sample-download.htm#:~:text=Requirement%20Traceability%20Matrix%20(RTM)%20is,are%20or%20will%20be%20tested.

Requirement Traceability Matrix (RTM) traces the User Requirement to the Test Cases via 2 types of requirements (BRD & FSD).

Business Requirement Document is the high level client API, while Functional Specification Document is from the developer's point of view.

FSD may map 1-1 or 1-M with a Test Case.

## Task

Your goal is to complete TC in Airtable.

1. Name: PROP-TC-#
2. Title: Copy from FSD Description if 1-1, if 1-M come up with suitable name

The BRD is the `describe` block in jest, while TC is the `it` block. 

3. Notes: add optional notes
4. Assign Modules & FSD

## Example

Create a PR for each BRD, put the ID in jest test inside a `[]`.  Put these inside `codelab/core/props/tests`, you'll have 4 test file because we have 4 BRD's.

`Prop-B-1.specs.tsx`

```ts
describe('User can specify props as objects [PROP-B-1]`, () => {
  // In this case the TC is same as FSD so 1-1, sometimes you may need to further split up FSD into multiple TC's
  it('should provide Node a method for building props [PROP-TC-1]', () => {
  })
})
```

## Motivation

We need a central location to keep track of all the high level requirements, and to verify those requirements are working, we have a mapping to test cases.

This allows me to focus on the business requirements while you are able to help me execute them.

## Caveats

The requirements are not set in stone by any means, there may be changes requirements. Since you're the one writing the tests, you'll have a better idea of what requirements need to be added/changed etc. Let me know if some parts of issues.

--------

Let me know if you have any questions! As this is a new workflow we'll be trying out, I am learning more about this as well.

**Comment by VienNguyen24hdev** [comment]
via Hubstaff
User: Nguyen Luong Vien

Project: Codelab - https://app.hubstaff.com/projects/1093588
Date Range: 09/14/20 - 09/22/20
Work session total: 31:51:50
Billable: Yes

Grand total: 31:51:50
