### ISSUE TITLE
Integration React Query component

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#1005]
https://react-query.tanstack.com/

Also integrate with our lambda module to add data for rendering.

**Comment by antonmihaylov** [comment]
TODO:
- [ ] ReactQuery Atom
- [ ] Figure out how exactly to pass results from ReactQuery atom down
- [ ] Lambda integration

**Comment by angelwong0963** [comment]
via Hubstaff
User: Angel Wong

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 08/05/21 - 08/05/21
Work session total: 0:12:36
Billable: Yes

Grand total: 4:06:32

**Comment by antonmihaylov** [comment]
via Hubstaff
User: Anton Mihaylov

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 08/05/21 - 08/05/21
Work session total: 3:53:56
Billable: Yes

Grand total: 4:06:32
