### ISSUE TITLE
Seeder for atoms

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#1008]
<img width="860" alt="codelab_–_seeder_service_ts_and_New_Issue_·_codelab-ai_codelab_ai" src="https://user-images.githubusercontent.com/26264925/128403599-d84612d4-df4b-4851-94a7-d957627a1323.png">

1. Seed primitive type, I've modifed get-type to search by name, so we can check for existence of primitive types like `String`, `Boolean`. There will every only be 1 for each user account (in future we'll have 1 for all user accounts). We'll use get-type query to check for existence, then seed as needed.
2. We'll go through each antd data sets, and construct all the primitive types first. The enum types may be more difficult, so we could save that for later on. Goal is to unblock the seeder so we can proceed with features
3. We'll could modify field or interface to create from a single json data, whichever seems the most sensible. This way we don't have to keep track of id's and do assignment in the seeder script.

---

`yarn cli seed`

**Comment by antonmihaylov** [comment]
via Hubstaff
User: Anton Mihaylov

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 08/06/21 - 08/08/21
Work session total: 9:32:33
Billable: Yes

Grand total: 9:32:33
