### ISSUE TITLE
Local state management

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#1014]
We'll want to come up with an architecture for local state management

In this article, https://www.apollographql.com/blog/apollo-client/architecture/client-side-architecture-basics/, state is broken down into `local (component), shared local (global), remote (global), meta, and router`

My first take is that we could create our own Recoil component that uses renderProps to pass down props to children component, since it may be difficult to allow users to add hooks to components.

Then we could use recoil to handle all local state

Let me know your thoughts on this

**Comment by antonmihaylov** [comment]
via Hubstaff
User: Anton Mihaylov

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 08/09/21 - 08/09/21
Work session total: 2:36:27
Billable: Yes

Grand total: 2:36:27
