### ISSUE TITLE
CRUD App

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#1020]
Do a simple crud app with GraphCMS, you can create a free account.

Create a single model with some fields, then connect the graphql endpoint to our Query component.

Create modal forms, and a table with update/delete buttons, both of which bring up a modal.

---

Essentially how we've been building our UI. This will be a simple crud app to test what features we are lacking.

**Comment by antonmihaylov** [comment]
continuing with #1060

**Comment by antonmihaylov** [comment]
via Hubstaff
User: Anton Mihaylov

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 08/10/21 - 08/22/21
Work session total: 30:16:07
Billable: Yes

Grand total: 30:16:07
