### ISSUE TITLE
PageData atom

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#1024]
Check out Query atom, it's a component for loading external data & binding it to other components.

https://codelabai.slack.com/archives/CR93U8XFH/p1628176048000300

Since Page data is an internal data, we'll need to provide access to this data via an atom.

I would suggest this pattern for any internal meta data that needs to be accessed, but for now we could create a PageData atom.

---

Similar to that demo, we'll load data (but internal data) & bind to our Link atom

**Comment by angelwong0963** [comment]
via Hubstaff
User: Angel Wong

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 08/12/21 - 08/19/21
Work session total: 6:42:40
Billable: Yes

Grand total: 6:42:40
