### ISSUE TITLE
element-tree.transformer.ts

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#1042]
Do we need the context to keep track of duplicate atoms? Why not just run a filter before returning the array

**Comment by antonmihaylov** [comment]
Mainly because the duplicated atoms after the first occurrence will be empty (or just with uid, without all other fields). So we need to assign them in those cases

**Comment by webberwang** [comment]
What about doing a filter & checking with items only have uid, then we could fetch the remaining info?

**Comment by antonmihaylov** [comment]
Why fetch duplicates when we already have them? Maybe I'm not explaining the issue well. Try in the playground to create 2 Elements with the same exact atom. Then try to fetch both Elements in 1 query to see what the results are
