### ISSUE TITLE
Fix rendering and prop mapper issue

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#1043]
- ### Fix the rendering mechanism in the `renderFactory()` method.

> https://github.com/codelab-ai/codelab.ai/blob/64bda14a643dd6b0ca65d8c33106dd45b4a4cffb/libs/frontend/modules/builder/src/renderer/renderFactory.tsx#L159
> 
> The `AntDesignMenuItem` is blinking when rendering. 
> To fix this, it is needed to convert the JSX to normal JavaScript function. 
> ![image](https://user-images.githubusercontent.com/85784065/129876413-d0b7241e-0c5c-413b-bd6e-ea68066d6f00.png)
> This will save the extra wrapper element.

> The reason of blinking: 
> ... > Menu > Wrapper Element > MenuItem

### - Fix the Prop Mapper not to use context
> Since we removed the wrapper element created by `<RenderElement />` in the `renderFactory()` method by above fix, there is no way to use context API for getting prop mapping inside the `RenderElement` method.
We need to update the Prop Mapper in the way of passing props down as function arguments

**Comment by angelwong0963** [comment]
via Hubstaff
User: Angel Wong

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 08/15/21 - 08/20/21
Work session total: 21:23:33
Billable: Yes

Grand total: 21:23:33
