### ISSUE TITLE
Refactor root index for modules to use named exports

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#105]
The dependencies between each module is hard to tell when looking at `export *`, if we have named exports we know exactly which function is used by other modules.

Refactor each module to named exports. Only the *root* index of each module is required of this change, since this is the boundary between each module

**Comment by VienNguyen24hdev** [comment]
via Hubstaff
User: Nguyen Luong Vien

Project: Codelab - https://app.hubstaff.com/projects/1093588
Date Range: 09/14/20 - 09/15/20
Work session total: 2:21:50
Billable: Yes

Grand total: 2:21:50

**Comment by webberwang** [comment]
Is there a need to use `export type`?
