### ISSUE TITLE
Try out runtime codegen

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#1067]
https://github.com/piglovesyou/graphql-let#why-this-exists

**Comment by antonmihaylov** [comment]
closed by #1069

**Comment by antonmihaylov** [comment]
via Hubstaff
User: Anton Mihaylov

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 08/27/21 - 09/05/21
Work session total: 34:33:48
Billable: Yes

Grand total: 34:33:48
