### ISSUE TITLE
Cypress specs for Renderer

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#1075]
Run `nx e2e web-e2e --configuration=dev`

Create new integration `apps/web-e2e/src/integration/renderer.spects`

Then copy the json data source as the fixture, we'll load the fixture data instead of actually hitting the database.

https://docs.cypress.io/guides/guides/network-requests#Fixtures

We can visit `web/pages/apps/[appId]/pages/[pageId]/builder` in our cypress specs & load data using fixture.

---

This is a different approach than other cypress specs, where we manually create the components using the UI. We've already tested the forms for creating UI, and this fixture method is a more efficient way of testing whether our data source can render components.

We're testing our renderer, not the forms/ui.

---

This below won't be how we test, because we're using the `builder.tsx` page directly, but under the hood you can imagine this happening.

<img width="1417" alt="tslib_js_–_demo_index_tsx_and_127_0_0_1_3000_demo" src="https://user-images.githubusercontent.com/26264925/132018862-537eb192-58ec-4ae9-b79a-629b16a2b77d.png">

**Comment by AlexanderBelkin** [comment]
via Hubstaff
User: Alexander Belkin

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 09/06/21 - 09/07/21
Work session total: 11:35:54
Billable: Yes

Grand total: 11:35:54

**Comment by AlexanderBelkin** [comment]
via Hubstaff
User: Alexander Belkin

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 09/07/21 - 09/07/21
Work session total: 0:24:55
Billable: Yes

Grand total: 12:00:49
