### ISSUE TITLE
`eval` props behavior

### ISSUE THREAD

**Issue by aburtsev** [codelab-ai/codelab.ai#108]
@webberwang 
## Current Behavior

If wrap any component with Modal then basic prop passing becomes broke. By basic I mean known props (for ex. onClick for a button). 

## Expected Behavior

The modal component should work consistently with others.

## Steps to Reproduce

Please find the example story called modal -> "With Form" in [branch in fork](https://github.com/aburtsev/codelab.ai/tree/modal-form-bug).

**Comment by webberwang** [comment]
Fixed by #109, issue is that we need to specify `renderProps: ['leaf', 'eval']'` for a function to pass more than 1 level

**Comment by aburtsev** [comment]
@webberwang  But in the current setup, all basic props passed through multiple levels, but if you wrap something with Modal. That this behavior is breaking. Please have a look at this [example](https://github.com/aburtsev/codelab.ai/commit/a243517b7fb47ca98f03e93761b2bbff31bbb56a) . If you remove 'Modal' wrapper than everything will work as expected. So to be consistent it should or not work in every case (=without renderProps should be passed only through 1 level) or work in all cases (=every basic props should be passed through all levels)

**Comment by webberwang** [comment]
Props should only pass 1 level down without specifying renderProps, could you show me where it is passing down multiple levels?

**Comment by aburtsev** [comment]
> @aburtsev Props shouldn't pass to children if we don't specify renderProps, could you show me where it is passed down?

@webberwang please have a look an example "BasicPropsPassedInDeep" in #114

**Comment by webberwang** [comment]
@aburtsev I see now, thanks for catching this. I have added `PROP-TC-13` & `PROP-TC-14` to check for this

**Comment by aburtsev** [comment]
> Fixed by #109, issue is that we need to specify `renderProps: ['leaf', 'eval']'` for a function to pass more than 1 level

It will be fixed by #109? I've tried to use it and such chaining doesn't work

**Comment by webberwang** [comment]
> > Fixed by #109, issue is that we need to specify `renderProps: ['leaf', 'eval']'` for a function to pass more than 1 level
> 
> It will be fixed by #109? I've tried to use it and such chaining doesn't work

I meant will be fixed, is this a blocker for you?

**Comment by webberwang** [comment]
Closed by #140

**Comment by VienNguyen24hdev** [comment]
via Hubstaff
User: Nguyen Luong Vien

Project: Codelab - https://app.hubstaff.com/projects/1093588
Date Range: 09/22/20 - 09/22/20
Work session total: 0:23:15
Billable: Yes

Grand total: 0:23:15
