### ISSUE TITLE
RenderProps improvements

### ISSUE THREAD

**Issue by aburtsev** [codelab-ai/codelab.ai#109]
@webberwang 

## Description
All examples exist in stories for "props" in the following [branch](https://github.com/aburtsev/codelab.ai/tree/render-props-improvements)
1. RenderProps should be firing the same way as other regular callbacks. Currently you need to add ".value" to be able to fire cb (regular callback firing with "this.props.regularCb()", renderProps callback firing with "this.props.renderPropsCb.value()"). (see example of usage in "External Prop Cb" case
2. RenderProps callbacks loosing context. Please see the example in the "External Prop And Ctx Cb" case. If you comment renderProps:'eval" everything will be fine. It'll be more consistent if context will not be changed regarding to renderProps value
3. RenderProps should eval custom functions. Currently if you try to pass some function declared via JSON with renderProps set to 'leaf', it'll not be compiled and remain string instead of function. Please see the example in the "Internal Leaf Prop Custom Cb"

**Comment by webberwang** [comment]
I searched for the examples like `External Prop Cb` in project but doesn't get any matches. What is the exact string?

**Comment by webberwang** [comment]
1. prop value needs to be object in order to specify renderProps, we'll add some wrapper in the future, this isn't too crucial for now but will add to a list of improvements for future. 

2. for `ctx`, you actually need to specify an object of it's own

```
ctx: {
  propKey: {}
}
```

3. that is true, we actually do chaining to accomplish this

```
renderProps: ['leaf', 'eval']
```

We're in the middle of refactoring & adding docs, but this should be functional for now

**Comment by aburtsev** [comment]
I used to use WebStorm with VIM, VSCode with VIM, and everywhere VIM is 3rd party citizen. And not works well, also the key binding is messed with IDE key bindings. Recently I've heard about [this integration of NeoVIm](https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim) in VSCode. (You can check it if you like vsCode). 
About ESLint integration I'll set up it.

**Comment by aburtsev** [comment]
>     1. prop value needs to be object in order to specify renderProps, we'll add some wrapper in the future, this isn't too crucial for now but will add to a list of improvements for future.

I understand that it should be an object to specify renderProps, but it will be great if you cannot distinguish it when you use it. I mean for ex. if at some point you decided to change some method to be renderProp you will need to refactor in all cases of usage (I mean change "this.props.method()" to "this.props.method.value()) and vice versa.

**Comment by aburtsev** [comment]
>     2\. I'm actually thinking of taking out `ctx` & just having client use provider when needing to provide context. this creates less code & makes everything more consistent

So I shouldn't use 'ctx'? Or right now I can?
And please have a look at my example "externalPropAndCtxCb". It's not about context, it's about how context is changing when you specify "renderProps"

**Comment by webberwang** [comment]
> > ```
> > 1. prop value needs to be object in order to specify renderProps, we'll add some wrapper in the future, this isn't too crucial for now but will add to a list of improvements for future.
> > ```
> 
> I understand that it should be an object to specify renderProps, but it will be great if you cannot distinguish it when you use it. I mean for ex. if at some point you decided to change some method to be renderProp you will need to refactor in all cases of usage (I mean change "this.props.method()" to "this.props.method.value()) and vice versa.

Yeah no reason to use `ctx` we will take that out, the extra logic is buggy. #2 will be fixed by this as well

**Comment by webberwang** [comment]
> > ```
> > 1. prop value needs to be object in order to specify renderProps, we'll add some wrapper in the future, this isn't too crucial for now but will add to a list of improvements for future.
> > ```
> 
> I understand that it should be an object to specify renderProps, but it will be great if you cannot distinguish it when you use it. I mean for ex. if at some point you decided to change some method to be renderProp you will need to refactor in all cases of usage (I mean change "this.props.method()" to "this.props.method.value()) and vice versa.

I agree with this, I'll create an issue and put it in the pipeline https://github.com/codelab-ai/codelab.ai/issues/113

**Comment by aburtsev** [comment]
> > > ```
> > > 1. prop value needs to be object in order to specify renderProps, we'll add some wrapper in the future, this isn't too crucial for now but will add to a list of improvements for future.
> > > ```
> > 
> > 
> > I understand that it should be an object to specify renderProps, but it will be great if you cannot distinguish it when you use it. I mean for ex. if at some point you decided to change some method to be renderProp you will need to refactor in all cases of usage (I mean change "this.props.method()" to "this.props.method.value()) and vice versa.
> 
> Yeah no reason to use `ctx` we will take that out, the extra logic is buggy. # 2 will be fixed by this as well. Fixed by #100

If I don't use ctx, then where I should place logic for React Hooks? In all stories with we had we use ctx for this. So if we don't use ctx, then we need to place this logic outside of JSON-config, but in such way, it will no be such transferrable

**Comment by webberwang** [comment]
@VienNguyen24hdev is refactoring `Provider` so we can use that to pass props. Issue right now is removing `ctx` will make `Provider` lose its own context.

For now you can just use `ctx` approach, I'll let you know when we switch over

**Comment by webberwang** [comment]
Closed by #140
