### ISSUE TITLE
Cypress e2e failing

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#1158]
For the seeding step it keeps failing, I've increased the exec timeout, but seems to be failing still. Any ideas?

<img width="943" alt="Cursor_and_e2e__13838__-_codelab-ai_codelab_ai" src="https://user-images.githubusercontent.com/26264925/138007258-f042bd5f-4adf-47b0-aba3-d7e5d6ed9989.png">

**Comment by antonmihaylov** [comment]
Fixed this in #1163
The bottleneck was that we create a lot of atoms very quickly, and dgraph sends out 429
Added a CreateAtomsService service which creates atoms in bulk
