### ISSUE TITLE
Missing function getRunningOperationPromises

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#1194]
<img width="992" alt="index_tsx_—_codelab" src="https://user-images.githubusercontent.com/26264925/141417174-18befb49-e526-429b-9c35-641bdd000a6b.png">

<img width="862" alt="api_ts_—_codelab" src="https://user-images.githubusercontent.com/26264925/141417105-0dec2f54-5cdc-4db0-a625-16cc44fc4555.png">

**Comment by assimhabeek** [comment]
@webberwang did you installed the latest packages ?

**Comment by webberwang** [comment]
yeah happened trying to update to nrwl 13, but decided not to upgrade
