### ISSUE TITLE
Toolbox gets hidden with long tables

### ISSUE THREAD

**Issue by assimhabeek** [codelab-ai/codelab.ai#1213]
## Current Behavior

The toolbox gets hidden and requires scroll with long pages 
![image](https://user-images.githubusercontent.com/33001357/144764007-c7a424b2-4983-47c1-981f-b8f488821d75.png)

## Expected Behavior

The toolbox should be fixed with the view port

**Comment by antonmihaylov** [comment]
Fixed in #1209
