### ISSUE TITLE
Prop transformation tab issue

### ISSUE THREAD

**Issue by antonmihaylov** [codelab-ai/codelab.ai#1218]
When the code is edited, if autosave Is triggered when the code in the field is invalid, it will trigger an infinite loop and crash the tab

**Comment by assimhabeek** [comment]
As first results, I come up to the following running async calls such as mutations will cause that. I will need to investigate more

**Comment by antonmihaylov** [comment]
Found it, this file was the problem https://github.com/codelab-ai/codelab.ai/pull/1219/files#diff-35029b30a8c5db1bc404dbc12ceb723da6253d55766b94e55ac19258542c9d6eR14
