### ISSUE TITLE
Vercel failing on build

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#1228]
This issue popped up a couple times before

https://vercel.com/codelabai/codelab/uhQsBktz3rEgETrriCau72yJDuu7

<img width="912" alt="codelab_–_Deployment_Overview" src="https://user-images.githubusercontent.com/26264925/146292000-b6c4764f-7f21-4ddb-8bb1-bd8237db5727.png">

**Comment by 23kbps** [comment]
Fixed by updating settings on vercel for "Install command"
![image](https://user-images.githubusercontent.com/86248851/148002084-b4cba3d1-dbb3-42e3-a1da-45424f028f93.png)
