### ISSUE TITLE
Type, Constant Refactor

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#1255]
- [x] This seems more elegant https://stackoverflow.com/a/44313931/2159920, shared/abstract/types
- [x] Ctrl + f `props.data-id` to refactor to constant
- [x] extraElementProps https://github.com/codelab-ai/codelab.ai/blob/c926f8836d07d6d9d94e8862c22fdb8a53003a16/libs/frontend/modules/builder/src/renderer/pipes/propMapBindingsPipe.ts#L14 
- [x] Similar to extraElementProps, we do the same for `data-component-id`
- [x] use PropData interface do ctrl find for `Record<string, any>` and see if they could be substituted
- [x] Use constant (do ctrl + f on project)
![image](https://user-images.githubusercontent.com/26264925/148677686-ac6febe8-3417-4dd0-9e25-55b5dff2daea.png)
![image](https://user-images.githubusercontent.com/26264925/148677775-400a6afa-fd21-4877-ba3d-5284c0fb711e.png)
- [ ] Pipeline grouping https://github.com/codelab-ai/codelab.ai/pull/1237#discussion_r780752436

**Comment by assimhabeek** [comment]
Just a quick note. in an case like this
```
  const getElementId = (renderedElement: ReactElement):  Maybe<string> => {
    return get(renderedElement, 'props.data-id', undefined)
  }
```
We shouldn't create a constant. because it is just a property name in an object where its structure could change a lot 
```
  const getElementId = (renderedElement: ReactElement): Maybe<string> =>
    renderedElement?.props?.[DATA_ID]
```

Same applies for https://github.com/codelab-ai/codelab.ai/blob/fd007128715f73a89cc92feaa7f092b44e7984da/libs/frontend/modules/builder/src/renderer/pipes/extraElementPropsPipe.ts#L10

**Comment by webberwang** [comment]
> Just a quick note. in an case like this
> 
> ```
>   const getElementId = (renderedElement: ReactElement):  Maybe<string> => {
>     return get(renderedElement, 'props.data-id', undefined)
>   }
> ```
> 
> We shouldn't create a constant. because it is just a property name in an object where its structure could change a lot
> 
> ```
>   const getElementId = (renderedElement: ReactElement): Maybe<string> =>
>     renderedElement?.props?.[DATA_ID]
> ```
> 
> Same applies for
> 
> https://github.com/codelab-ai/codelab.ai/blob/fd007128715f73a89cc92feaa7f092b44e7984da/libs/frontend/modules/builder/src/renderer/pipes/extraElementPropsPipe.ts#L10

Right I mean to use constant `DATA_ID`, could do same for `extraElementProps` since that doesn't change `EXTRA_ELEMENT_PROPS`
