### ISSUE TITLE
Node form / table

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#141]
`web/pages/node` is a form, we'll have to connect it to the endpoint for creating nodes, then query to pull into table.

POST http://localhost:3333/api/v1/Node with json to create nodes, the GET http://localhost:3333/api/v1/Node to pull data into table.

For the columns we'll have nodeType, props, id, & children, parent

1. Filter by nodeType
2. Show tag with ID, clicking on ID will set table filter for id to that id

After POSTING, the table should update without refresh.

**Comment by VienNguyen24hdev** [comment]
via Hubstaff
User: Nguyen Luong Vien

Project: Codelab - https://app.hubstaff.com/projects/1093588
Date Range: 09/28/20 - 10/06/20
Work session total: 21:22:35
Billable: Yes

Grand total: 21:22:35
