### ISSUE TITLE
Enable form hooks

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#142]
To add custom component follow these steps

1.  <img width="824" alt="element-factory_tsx_—_codelab__Workspace_" src="https://user-images.githubusercontent.com/26264925/94500789-07699380-01b5-11eb-93f9-8306ca631189.png">

2. <img width="1011" alt="Form_tsx_—_codelab__Workspace_" src="https://user-images.githubusercontent.com/26264925/94500837-2536f880-01b5-11eb-9509-1ffa5032272c.png">

3. Inside `Form`, we should using binding form hook ` const [form] = Form.useForm();`, then pass `form` as a leaf renderProp so all children component can access. Then you can access `this.              form.resetFields();` on the form success callback

**Comment by webberwang** [comment]
@aburtsev I pushed the new refactor for the props, not sure if it allows us to create the custom form component.

If not could you look into modifying props flow so we are able to add the form hook as a custom component?

**Comment by webberwang** [comment]
@aburtsev hey did you have any questions regarding this task?

**Comment by aburtsev** [comment]
@webberwang I've seen the result of refactoring and that currently, I'm able to use form hooks. I'll try to implement a custom form that meets the requirements of the description.
