### ISSUE TITLE
Add parent field in node form

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#143]
Add a `parent` field in the node form, which uses a select box & uses a list of nodes as the options (use id is okay for now)

**Comment by VienNguyen24hdev** [comment]
via Hubstaff
User: Nguyen Luong Vien

Project: Codelab - https://app.hubstaff.com/projects/1093588
Date Range: 09/28/20 - 09/29/20
Work session total: 2:06:50
Billable: Yes

Grand total: 2:06:50
