### ISSUE TITLE
Write Cypress tests for node form

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#144]
1. `nx serve web` start our web server
2. `nx e2e web-e2e --watch` start cypress

I have set up cypress to assert that button exists on `/node` page in `web-e2e` integration. We want a full flow for adding node.

Something like this.

1. Click on button shows form 
2. choose React
3. choose Button
4. Add prop.
5. use cypress network request to assert form submit data json structure. (we don't have an endpoint for now, so we can mock it)

Use findByLabel, then findByRole, or sometimes it may be best to create a custom Cy.Command such as the button. The default react testing methods didn't work for some reason, but creating our own commands gives us our own api to use.

Another custom command I would create is for a form select box, this is something we use often. We want to pick a select box by label, and after clicking on it we want to assert all available options. Then after selecting an option, we should see the value has changed.

**Comment by webberwang** [comment]
@aburtsev hey was there a PR for this? I remember adding comments but couldn’t find it for some reason

**Comment by aburtsev** [comment]
@webberwang We've already merged PR with e2e tests. Can we close this issue?
