### ISSUE TITLE
Refactor to use Service, Repository

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#153]
- [x] 10.1.20 Refactor to use service + repository 
- [x] 10.6.20 Create new branch & new PR to fix these comments https://github.com/codelab-ai/codelab.ai/pull/156
- [x] 10.7.20 I had missed these https://github.com/codelab-ai/codelab.ai/pull/156#pullrequestreview-503400073

At a high level, our `web` application should not contain any domain specific logic. These logic include CRUD logic, data mapping logic, form validation logic etc.

The `web` UI should interact with `services` only.

Services will then call the infrastructure layer, which includes repositories.

<img width="922" alt="codelab-reclone_–_node-service_ts" src="https://user-images.githubusercontent.com/26264925/94884284-e9ed3180-0421-11eb-94c1-40f0391166b8.png">

**Comment by webberwang** [comment]
Create new branch & new PR to fix these comments https://github.com/codelab-ai/codelab.ai/pull/156

**Comment by VienNguyen24hdev** [comment]
via Hubstaff
User: Nguyen Luong Vien

Project: Codelab - https://app.hubstaff.com/projects/1093588
Date Range: 10/02/20 - 10/07/20
Work session total: 15:48:20
Billable: Yes

Grand total: 15:48:20
