### ISSUE TITLE
Model/Schema factory to restify integration

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#159]
Allow the node modal form + table to configure the model + schema that restify is using

<img width="1082" alt="restify_module_ts_—_codelab__Workspace_" src="https://user-images.githubusercontent.com/26264925/95282129-a58cd780-080d-11eb-86bf-f2385c97a59b.png">

**Comment by VienNguyen24hdev** [comment]
via Hubstaff
User: Nguyen Luong Vien

Project: Codelab - https://app.hubstaff.com/projects/1093588
Date Range: 10/07/20 - 10/14/20
Work session total: 27:53:52
Billable: Yes

Grand total: 27:53:52
