### ISSUE TITLE
Integrate layout to pages/index

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#178]
- [x] Layout: Integrate layout to pages/index + edit form
- [x] Table: add table action
- [x] Edit Form

## Layout

At index we are re-doing the node page with a better setup.

We are creating each component individually (specifying it's props), then composing them.

<img width="1256" alt="node_tsx_—_codelab__Workspace_" src="https://user-images.githubusercontent.com/26264925/96052921-578e5a00-0e33-11eb-96e9-9d280ac952a0.png">

Before we passed in all handlers at root level, but now we have clearer separation of handlers (we can pass directly to component that uses it).

All handlers also use the actor model.

You'll want to integrate the layout like so. The header, footer, sidebar, we can use a dummy one (could just re-use the existing stories data). But the important part is to create a layout actor (like modal actor), that will keep the state of the sidebar.

In our case, should we combine the actor for modal & layout instead of having separate actors to save boilerplate code? These are all UI state so may it is a good idea to have the same actor for those.

Let me know your thoughts

## Table

The action column has been commented out. These buttons should be using the actor model

<img width="852" alt="Table_tsx_—_codelab__Workspace_" src="https://user-images.githubusercontent.com/26264925/96053678-d1731300-0e34-11eb-9c3e-bc0e6bc071b2.png">

## Edit Form

The old edit form `pages/node` use local hooks to keep state of current node we are editing. We want to move this to Node actor for the new one at `pages/index`

**Comment by aburtsev** [comment]
> In our case, should we combine the actor for modal & layout instead of having separate actors to save boilerplate code? These are all UI state so may it is a good idea to have the same actor for those.

What do you mean by combine? Use the same states and messages? Like, create some generator of machines? 
![image](https://user-images.githubusercontent.com/3891411/96157315-d4483380-0f1a-11eb-984a-43240f488035.png)

They both UIs. But they have different contexts and different actions. So I think it's better to keep them separate.

**Comment by aburtsev** [comment]
I need to think a little bit more and make some experiments with machines. Probably we can use withConfig to extend machines with specific behavior. I mean we can specify the core of the machine ( = set of core states and messages) and then extend them to follow the behavior and the context specific to each component. But do we need such kind of generalization?

**Comment by aburtsev** [comment]
![image](https://user-images.githubusercontent.com/3891411/96160800-1b382800-0f1f-11eb-9ab8-a5f8af6104fc.png)

And I think it will be convenient to use generalized messages. It will give us the ability to make the decision about the next action based on the current state and avoid unnecessary loops (what sense to open opened modal?).
@webberwang  What do you think about this?

**Comment by webberwang** [comment]
@aburtsev yeah sure let's use `TOGGLE`

**Comment by webberwang** [comment]
> > In our case, should we combine the actor for modal & layout instead of having separate actors to save boilerplate code? These are all UI state so may it is a good idea to have the same actor for those.
> 
> What do you mean by combine? Use the same states and messages? Like, create some generator of machines?
> ![image](https://user-images.githubusercontent.com/3891411/96157315-d4483380-0f1a-11eb-984a-43240f488035.png)
> 
> They both UIs. But they have different contexts and different actions. So I think it's better to keep them separate.

I just mean to use same machine for both modal state & sidebar state for example. I do think it's better to keep separate as well

**Comment by webberwang** [comment]
> I need to think a little bit more and make some experiments with machines. Probably we can use withConfig to extend machines with specific behavior. I mean we can specify the core of the machine ( = set of core states and messages) and then extend them to follow the behavior and the context specific to each component. But do we need such kind of generalization?

I can't think of any generalization as of now. We can always refactor later once we see a pattern emerge
