### ISSUE TITLE
Add `React.RenderComponent`

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#182]
I've created a custom `React.Query` component that passes the results of fetch into the children as props.

We'll need to create a children component that returns a function as component to access the data within the children

I'd call it something like `React.RenderComponent`

<img width="429" alt="graphql_tsx_—_codelab__Workspace_" src="https://user-images.githubusercontent.com/26264925/96200884-f8eade00-0f0f-11eb-8d73-ac0d48ce51b4.png">

**Comment by VienNguyen24hdev** [comment]
via Hubstaff
User: Nguyen Luong Vien

Project: Codelab - https://app.hubstaff.com/projects/1093588
Date Range: 10/15/20 - 10/20/20
Work session total: 4:26:04
Billable: Yes

Grand total: 4:26:04
