### ISSUE TITLE
Allow array to be mapped to components

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#183]
For the node table children column, instead of a nested table we want to render a list.

We'll need some sort of way to map to an array of components.

## Suggestion

This isn't thought out so you'll have to come up with a design.

Maybe a mapper component `React.Mapper` that allows 

```
type: 'React.Mapper',
children: [{ 
  type: 'React.Tag'
}]
```

Then refactor the node table to use a list instead of a table for the nested children nodes column

**Comment by VienNguyen24hdev** [comment]
via Hubstaff
User: Nguyen Luong Vien

Project: Codelab - https://app.hubstaff.com/projects/1093588
Date Range: 10/19/20 - 10/20/20
Work session total: 7:14:39
Billable: Yes

Grand total: 7:14:39
