### ISSUE TITLE
Modify select to search select for node form on `pages/node.tsx`

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#184]
https://ant.design/components/select/#components-select-demo-search

For `Type` field, which is showing the list of react components

**Comment by VienNguyen24hdev** [comment]
via Hubstaff
User: Nguyen Luong Vien

Project: Codelab - https://app.hubstaff.com/projects/1093588
Date Range: 10/23/20 - 10/26/20
Work session total: 4:26:11
Billable: Yes

Grand total: 4:26:11
