### ISSUE TITLE
Setup project so you can run it

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#191]
<img width="895" alt="Playground_-_http___localhost_4000_graphql_and_Compare_·_codelab-ai_codelab_ai" src="https://user-images.githubusercontent.com/26264925/96637124-1c78a480-12d3-11eb-8eef-fd1a95b83eef.png">

This should work

**Comment by artonio** [comment]
Got it to work. Was able to create a node using GraphQL playground. Strange error when running the project, although everything work so far, not sure what that is all about yet.

Error checking for changes to service definitions: Couldn't load service definitions for "prop-service" at http://localhost:4001/graphql: 500: Internal Server Error
This data graph is missing a valid configuration. Couldn't load service definitions for "prop-service" at http://localhost:4001/graphql: 500: Internal Server Error

**Comment by webberwang** [comment]
nx serve api-services-props to run that alone, any addition error messages you see?

**Comment by artonio** [comment]
ran the command above, the server started successfully, no errors. The GraphQL at the specified URL loads fine and the schema looks like this

directive @specifiedBy(url: String!) on SCALAR
directive @key(fields: String!) on OBJECT | INTERFACE
directive @extends on OBJECT | INTERFACE
directive @external on OBJECT | FIELD_DEFINITION
directive @requires(fields: String!) on FIELD_DEFINITION
directive @provides(fields: String!) on FIELD_DEFINITION
scalar _Any

union _Entity = Prop
type _Service {
  sdl: String
}

scalar JSONObject

type Prop {
  id: ID!
  props: JSONObject!
}

type Query {
  _entities(representations: [_Any!]!): [_Entity]!
  _service: _Service!
  props(id: Float!): Prop!
}

Also, after running yarn start, I was able to successfully create a node and the GraphQL Playground worked fine.

**Comment by artonio** [comment]
Just did a pull from master and reviewed the code changes, now i'm getting

Error checking for changes to service definitions: Couldn't load service definitions for "api-services-props" at http://localhost:4001/graphql: request to http://localhost:4001/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:4001
This data graph is missing a valid configuration. Couldn't load service definitions for "api-services-props" at http://localhost:4001/graphql: request to http://localhost:4001/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:4001

in the log. but still everything works fine

**Comment by webberwang** [comment]
If 4001 doesn’t load what does nx serve api-services-props show in terms on console errors

**Comment by artonio** [comment]
> If 4001 doesn’t load what does nx serve api-services-props show in terms on console errors

ENOENT: no such file or directory, open '/Users/antonsukhovatkin/DEV/upwork/nestjs/codelab.ai/dist/apps/api/services/props/hero/hero.proto' +7ms
Error: The invalid .proto definition (file not found)
    at ServerGrpc.loadProto (/Users/antonsukhovatkin/DEV/upwork/nestjs/codelab.ai/node_modules/@nestjs/microservices/server/server-grpc.js:254:39)
    at ServerGrpc.bindEvents (/Users/antonsukhovatkin/DEV/upwork/nestjs/codelab.ai/node_modules/@nestjs/microservices/server/server-grpc.js:35:34)
    at ServerGrpc.start (/Users/antonsukhovatkin/DEV/upwork/nestjs/codelab.ai/node_modules/@nestjs/microservices/server/server-grpc.js:30:20)
    at ServerGrpc.listen (/Users/antonsukhovatkin/DEV/upwork/nestjs/codelab.ai/node_modules/@nestjs/microservices/server/server-grpc.js:27:20)

**Comment by webberwang** [comment]
Okay I see the problem now will push fix soon

**Comment by webberwang** [comment]
Yep looks like it doesn't affect functionality for your current task that I just assigned #202
