### ISSUE TITLE
Refactor enum

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#195]
Enums & string key with dots was throwing error when converting it to GraphQL enum types, so we'll need to refactor our enum

Uncomment this block & remove the string value

<img width="539" alt="node-enum_ts_—_codelab__Workspace_" src="https://user-images.githubusercontent.com/26264925/96655252-e0a10780-12f1-11eb-9556-b904a9a933cc.png">

```typescript
export enum NodeType {
  React_Fragment,
  React_Html_Div,
}
```

Then update all JSON object to use enum instead of string. This is easier to refactor down the road. We should use enum for hardcoded json, even though we'll use string for api data.

-------

For `__type: ['Eval', 'Single',]` etc let's use an enum as well

```typescript
enum PropType {
  Eval = 'Eval',
  Single = 'Single'
}
```
& update all the data files as well.

-----

We shouldn't have used string in ts files even though we'll be using string for user created components.

This will make our current hardcoded even more type safe & reduce errors.

**Comment by webberwang** [comment]
nice work has been merged

**Comment by VienNguyen24hdev** [comment]
via Hubstaff
User: Nguyen Luong Vien

Project: Codelab - https://app.hubstaff.com/projects/1093588
Date Range: 10/20/20 - 10/22/20
Work session total: 7:36:35
Billable: Yes

Grand total: 7:36:35
