### ISSUE TITLE
yarn build warning error

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#196]
`yarn build` triggers error when we `export *` for types. I think related to tsconfig.json & typescript

Look for a solution that doesn't require us to define `export type` keyword

<img width="693" alt="yarn_build" src="https://user-images.githubusercontent.com/26264925/96664730-4d270100-1308-11eb-921a-0f386133e31c.png">

**Comment by VienNguyen24hdev** [comment]
via Hubstaff
User: Nguyen Luong Vien

Project: Codelab - https://app.hubstaff.com/projects/1093588
Date Range: 10/22/20 - 10/23/20
Work session total: 2:18:19
Billable: Yes

Grand total: 2:18:19
