### ISSUE TITLE
User Module

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#202]
1. Follow the `Dev Tools` section to generate `libs/api/services/user` using `@codelab/schematics:nest-lib`. This is our Nest.js UserModule--

2. we'll store User model in Neo4j

3. Enable federation at `apps/api/federation/user` and add to gateway

4. add authentication https://docs.nestjs.com/techniques/authentication

<img width="485" alt="node_input_ts_—_codelab__Workspace_" src="https://user-images.githubusercontent.com/26264925/96837125-c43cc200-13fa-11eb-9583-fddd0d740370.png">

5. Create 2 files `queries.graphql`, `mutation.graphql` in `apps/api/federation/user/src/graphql`

Put the queries there you use for manually testing out CRUD operations

6. Also add some tests https://www.apollographql.com/docs/apollo-server/testing/testing/

**Comment by artonio** [comment]
Hasura looks cool. But it only works with Postgres atm. You ok with storing user data in Postgres and not Mongo?

**Comment by webberwang** [comment]
Yeah Postgress actually has object store as well

**Comment by artonio** [comment]
DB Schema
```typescript
interface Edge {
  id: string
  source: string
  target: string
  props?: object
}
interface Vertex {
  id: string
  props?: object
}
interface Graph {
  edges: Array<Edge>
  vertices: Array<Vertex>
}
interface User {
  graphs: Array<Graph>
  email: string
  password: string
}
```
