### ISSUE TITLE
Create terraform settings for kubernetes cluster

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#232]
- [X] 10/30 Add cluster to Terraform

For now let's create a digital ocean cluster with 1 node in the pool, use the lowest config machine.

You can deploy an nginx docker image & just have welcome screen displayed to see it working.

Under `.terraform` of project root, ends up like `.terraform/.terraform/plugins` after init

This is a base cluster with nothing but the nginx image installed (no ambassador etc)

Just use nodePort to expose port for now, this is more focused on the terraform config, put the shell script I should run to provision under `.terraform/run.sh`
---
- [x] 11/4 Add prod db to Terraform
- [ ] 11/5 Add staging db to Staging cluster (via helm chart)
- [ ] 11/5 Deploy ambassador on Production cluster
Add 1 postgres database to terraform settings, use the lowest cost plan (SFO2) for all

**Comment by nutshell113** [comment]
@webberwang terraform requires an object storage to store its state file. Either AWS S3, Azure Storage or Digital Ocean Space work fine. Shall we use DO Space ?

**Comment by nutshell113** [comment]
@webberwang , tf code was initialized at https://github.com/codelab-ai/codelab.ai/pull/253. I also include https://github.com/codelab-ai/codelab.ai/blob/terraform/.terraform/run.sh and https://github.com/codelab-ai/codelab.ai/blob/terraform/.terraform/README.md to let you easier when provisioning.

**Comment by webberwang** [comment]
Closed by #253
