### ISSUE TITLE
Docker run not working with entrypoint

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#233]
## Docker compose works

- Copy `.env.example` to `.env`
- `yarn docker:up web` then visit `http://localhost:3000`

should show

<img width="856" alt="yarn_docker_up_web" src="https://user-images.githubusercontent.com/26264925/97832922-e51dd680-1c88-11eb-9017-91c8e5e909f8.png">

<img width="895" alt="localhost_3000_and_Kubernetic_-_The_Desktop_Client_for_Kubernetes" src="https://user-images.githubusercontent.com/26264925/97832928-e9e28a80-1c88-11eb-97bb-22d7c06c39b3.png">

## Docker run not working

`./.docker/run.sh` doesn't work with entrypoint

It is running same script basically

<img width="943" alt="webber_webbers-mbp____Sites_Codelab_codelab" src="https://user-images.githubusercontent.com/26264925/97832975-07afef80-1c89-11eb-8d3b-196f4ff0458e.png">

---------

<img width="1464" alt="run_sh_—_codelab__Workspace_" src="https://user-images.githubusercontent.com/26264925/97817413-3316e800-1c51-11eb-9c02-3d4671baf0c7.png">

## Goal

make `./.docker/run.sh` work same as docker-compose method

**Comment by nutshell113** [comment]
hey @webberwang , we can use cm overriding like this one: https://github.com/codelab-ai/codelab.ai/pull/238

**Comment by webberwang** [comment]
Closed by #238
