### ISSUE TITLE
CircleCI pipeline

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#236]
I didn't mention CircleCI in the original job post, but it is related to dev ops, so hopefully you can help out with this task as well.

Read docs on circleci setup `documentation/ci-cd/circleci.md`

## Issues

Inside `.circleci/config.yml`

Disable dev workflow, and enable staging workflow (by commenting & uncommenting):

- Set `filters-dev.filters.branches.only` to `/^never$/`
- Set `filters-staging.filters.branches.only` to `/^.*$/`

Now `app-staging` workflow will run each time code is pushed to a branch with a PR open.

If you run this now, you'll get some error about incorrect node version. Search for `Set node version`, uncomment that block.

## Missing Env

Now if you run again, the `filters-staging` should have an error about missing `.env` file

https://discuss.circleci.com/t/pass-env-vars-to-docker-containers-in-circle-2-0/17827/8

## NVM not available

But if we run `app-dev` workflow by reverting the filters above, we'll get an error that `nvm` is not available

This happens because the 2 workflow have different executors, we'll need a way to set node version that works across both executor environments

Either we'll have to install NVM before using it, or we could find some other way to set node version.

------------

- [ ] Missing .env file
- [ ] NVM issue

**Comment by lphan-clv** [comment]
[x] Missing .env file 
[ ] NVM issue

**Comment by nutshell113** [comment]
@webberwang both issues was fixed & tested on https://github.com/codelab-ai/codelab.ai/pull/241 .Currently it's stuck on lint of dev-worklows, seems they are just commits issues. Pls take a look at diff.
