### ISSUE TITLE
Setup cert-manager with DO

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#239]
https://cert-manager.io/docs/configuration/acme/dns01/digitalocean/

Let me know what info I need to update dns with

--------------

Came across this

<img width="1101" alt="Ambassador_Edge_Stack_Edge_Policy_Console" src="https://user-images.githubusercontent.com/26264925/97852652-e0b6e500-1cab-11eb-87f0-84d01d41ac6a.png">

**Comment by nutshell113** [comment]
https://github.com/codelab-ai/codelab.ai/pull/265 - related PR was created.
