### ISSUE TITLE
Setup argocd server

### ISSUE THREAD

**Issue by nutshell113** [codelab-ai/codelab.ai#258]
Use this helm chart to deploy argocd on prod-cluster https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd . It will be used for k8s deploying on both prod and staging environments

**Comment by webberwang** [comment]
@nutshell113 we'll need this first https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/

**Comment by nutshell113** [comment]
> @nutshell113 do we need this first https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/?
> 
> I would prefer a declarative setup for the user portion https://argoproj.github.io/argo-cd/user-guide/kustomize/

Yes, we'll use kustomize, sorry I pasted the wrong link of argocd helm chart (fixed).

**Comment by webberwang** [comment]
Closed by #286
