### ISSUE TITLE
Setup services

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#259]
1. `git checkout master`
2. `cp .env.example .env`
3. change `.env` with: 

```
CODELAB_ENV=staging
HASURA_GRAPHQL_URI=http://hasura:8080/v1/graphql
POSTGRES_HOST=postgres
```

4. `yarn docker:up hasura postgres-test`
5. `yarn docker:up api-graph`
6. visit `http://localhost:4004/graphql`, `docs` on right side should show schema

---
https://github.com/codelab-ai/codelab.ai/edit/master/documentation/ci-cd/environments.md

- [x] e2e env with docker database
- [x] staging with DO cloud db
- [x] staging with vault as env
- [x] production with DO cloud db

**Comment by webberwang** [comment]
<img width="1167" alt="•_Codelab_mdj_—_StarUML__UNREGISTERED_" src="https://user-images.githubusercontent.com/26264925/98224546-72bb2980-1f08-11eb-9636-54c7efe1be42.png">

**Comment by nutshell113** [comment]
![image](https://user-images.githubusercontent.com/16603476/99866787-9a87de00-2be6-11eb-8cab-61f9cec47fef.png)
It currently can run, now we need to deploy some needed services (hasura & postgres) to let it works 
- image tag: 0.02
- env: staging
- commit: https://github.com/codelab-ai/codelab.ai/pull/308/commits/222b3ffbc1c039c970c475f8a9012304ff511654

**Comment by nutshell113** [comment]
All ENVs were integrated to Vault.
