### ISSUE TITLE
Revised graph persistence model

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#262]
After some thought, we actually wouldn't use https://typeorm.io/#/tree-entities. Using TreeEntity would still create a tree-like data structure representation with parent/children (similar to Neo4j).

We actually want to represent data in a graph-like structure, which separates out into `vertexes` & `edges`. The `edges` hold the `source` & `target` then allow us to connect `vertexes` together to form a Graph.

Most graph libraries such as D3.js (https://github.com/d3/d3), and Cytoscape.js (https://github.com/cytoscape/cytoscape.js) both use the Graph representation.

https://github.com/d3/d3-force/tree/v2.1.1#links
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1c79245bb53715a4d24d53fd88d6f268cb14c0de/types/cytoscape/index.d.ts#L140-L153

-----------

Ultimately comes down to 2 models

```typescript
interface Edge {
  id: string
  source: string
  target: string
  props?: object
}
```

```typescript
interface Vertex {
  id: string
  props?: object
}
```

```typescript
interface Graph {
  edges: Array<Edge>
  vertices: Array<Vertex>
}
```

```typescript
interface User {
  graphs: Array<Graph>
  email: string
  password: string
}
```

Our ORM wouldn't know how to construct our Tree, so we'll defer to our core models to construct the tree. In fact Cytoscape.js does just that by default.

We pull out all the complexity into our application code, keeping our infrastructure as simple as possible

**Comment by artonio** [comment]
Moving this to Review. I'm going to work on UserModule next and incorporate the changes to DB schema in that ticket.
