### ISSUE TITLE
AntD Props Interface -> Json Schema

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#335]
Look into code generation from AntD interface to JSON-Schema using https://github.com/YousefED/typescript-json-schema

Move into https://nx.dev/latest/angular/workspace/generators/workspace-generators

**Comment by aburtsev** [comment]
One more lib
https://github.com/vega/ts-json-schema-generator

>  If you are looking for a library that uses the AST instead of the type hierarchy and therefore better support for type aliases, have a look at vega/ts-json-schema-generator.

**Comment by aburtsev** [comment]
> One more lib
> https://github.com/vega/ts-json-schema-generator
> 
> > If you are looking for a library that uses the AST instead of the type hierarchy and therefore better support for type aliases, have a look at vega/ts-json-schema-generator.

https://github.com/vega/ts-json-schema-generator/issues/209
Doesn't work with react dependent types
