### ISSUE TITLE
Run e2e tests for Ci

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#341]
Our CircleCI `test` job needs to run on our kubernetes cluster, since CircleCi environment doesn't have the right infrastructure (no database, no UI).

We'll also solve the issue with env vars and circleci if we run on kubernetes.

https://app.circleci.com/pipelines/github/codelab-ai/codelab.ai/1391/workflows/2e7dbb4d-0fdf-4016-a72a-183d8a19c80a/jobs/3627/parallel-runs/0/steps/0-108?invite=true

**Comment by nutshell113** [comment]
As discussed, now we're using public lb from staging cluster.
