### ISSUE TITLE
Manually rename LB

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#368]
![Codelab_project_-_DigitalOcean](https://user-images.githubusercontent.com/26264925/101283137-87037800-378d-11eb-835d-f5c08f72f494.png)

**Comment by nutshell113** [comment]
![image](https://user-images.githubusercontent.com/16603476/101971360-6773c000-3c63-11eb-9b8a-272aa7e2dc50.png)

Renamed, please see and merge: https://github.com/codelab-ai/codelab.ai/pull/386
