### ISSUE TITLE
Use recoil to create custom hook to easily share actors across components

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#374]
https://www.youtube.com/watch?v=_ISAA_Jt9kI&amp%3Bfeature=emb_title

Idea is to have a root machine that spawns actors (we currently have that), but we would create a custom hook to easily access actors across any component (we'll do this without context provider but with recoil).

`const [state, send] = useLayoutActor()`

`web/pages/_app.tsx`

<img width="948" alt="_app_tsx_—_codelab" src="https://user-images.githubusercontent.com/26264925/101888679-4e7be980-3b53-11eb-82dd-e43cada273f7.png">

------------

I ended up using a different implementation with react hooks & a single provider like before

Here's my finding...

Recoil requires us to call `useSetRecoilState` somewhere for it to know an update as occurred. Doesn't seem to play nicely with our event system.

Would like to see your conclusion

In any case I think it's good to explore this library as it does solve some issues for cross component state management

**Comment by aburtsev** [comment]
We can also consider jotai. The functionality that we need looks the same but the size is 6 times less and API is minimalistic https://github.com/pmndrs/jotai
