### ISSUE TITLE
Jwt Guard not parsing jwt headers

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#442]
The jwt tokens are correct, but guard isn't authorizing

![image](https://user-images.githubusercontent.com/26264925/103789924-6a10cd80-4ff5-11eb-8c46-c6e6bcfa0f60.png)

![image](https://user-images.githubusercontent.com/26264925/103790134-a80df180-4ff5-11eb-9091-2e3824d2e0d1.png)

**Comment by artonio** [comment]
JwtConfig.JWT_EXPIRY was read as a string, where is should be a number, fixed
