### ISSUE TITLE
Nextjs Page Auth Guard

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#476]
Goal is the create an auth guard for pages, so we show the users the home page if they're accessing `/apps` without logging in.

I first found https://github.com/nextauthjs/next-auth. Seems like a cool concept but we are using xstate for session data & have our own api's for authentication. Next-auth would be good to prototype a brand new project with any existing infrastructure.

I think we should fetch user data server side so we don't get a flicker for page (Next.js SSR feature). 

This is an auto-generated server side query to be used with SSR (https://graphql-code-generator.com/docs/plugins/typescript-apollo-next)

![image](https://user-images.githubusercontent.com/26264925/104685804-c1c3ce80-56b0-11eb-88bc-f1f94d114a0a.png)

The issue is that we don't have access to local storage at server side.

May need to use cookies instead per this discussion

https://github.com/vercel/next.js/discussions/17247

This method would also mean we run the auth check each time we load a page, incase jwt expires. Currently we only update user data on login/register, which may not be as ideal

Let me know your thoughts on how to implement auth guard for nextjs pages

**Comment by antonmihaylov** [comment]
We send the auth token in the headers if there is one every time we make a request, right? I think we can get it from there inside getServerSideProps. Then make an API request to getMe to check if it's valid and redirect if it isn't
