### ISSUE TITLE
Design form generator

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#539]
Goal is to specify decorators only on input class and for us to generate a form to import and use.

Things we’ll need

- Form title 
- Submit text
- Grid
- Mutation function (check out createPageForm)

Write some function/type interfaces and some pseudo code but don’t implement anything 

you can add them as comment here

**Comment by aburtsev** [comment]
**Option 1**
`export interface MutateParams {
  hookName: string
  baseOptions?: Apollo.MutationHookOptions
}


export interface FormDecorator {
  title?: string
  submitLabel?: string
  mutate?: MutateParams
}

export type FormDecoratorDetails = FormDecorator

export const form = (params: FormDecorator) => {
  console.log('here')
}
`

**Usage:**
`import { form, grid } from '@codelab/tools/generators/json-schema'

@form({
  title: 'DemoGrid',
  submitLabel: 'Submit',
  mutate: { hookName: 'useCreatePageMutation',
          baseOptions: {refetchQueries: [
            {
              query:...
            }
          ]}},
})
export class DemoGridFormInput {
  @grid({ order: 1, span: 12 })
  email1 = ''

  @grid({ order: 0, span: 16 })
  password0 = ''

  @grid({ order: 2, span: 8 })
  name2 = ''

  notGroupedField = ''
}
`

Drawback: we can't easily specify type for the baseOptions (it will be initialized with 'any'). We can pass types for data and variables in generic, but it will be very verbose

**Comment by aburtsev** [comment]
**Option 2**
```
export interface MutateParams2<T extends (...args: any) => any> {
  hook: T
  baseOptions?: Parameters<T>[0]
}
export interface FormDecorator2<T extends (...args: any) => any> {
  title?: string
  submitLabel?: string
  mutate?: MutateParams2<T>
}

export const formv2 = <T extends (...args: any) => any>(
  params: FormDecorator2<T>,
) => {
  console.log('here')
}
```

**Usage:**
```
import { formv2, grid } from '@codelab/tools/generators/json-schema'
import { useCreatePageMutation } from '@codelab/generated'

@formv2<typeof useCreatePageMutation>({
  title: 'DemoGrid',
  submitLabel: 'Submit',
  mutate: { hook: useCreatePageMutation, baseOptions: { refetchQueries: {...} } },
})
export class DemoGridFormInput {
  @grid({ order: 1, span: 12 })
  email1 = ''

  @grid({ order: 0, span: 16 })
  password0 = ''

  @grid({ order: 2, span: 8 })
  name2 = ''

  notGroupedField = ''
}
```

Drawback: Here we will have more type safety. But we coupled [..]Input.ts with graphQL generated code
