### ISSUE TITLE
Grid nested properties

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#554]
![image](https://user-images.githubusercontent.com/26264925/106592275-28941500-6504-11eb-9db7-1fc8951e3b5f.png)

![image](https://user-images.githubusercontent.com/26264925/106592307-35186d80-6504-11eb-9b5d-bed7d3ee52b6.png)

![image](https://user-images.githubusercontent.com/26264925/106592493-6bee8380-6504-11eb-85d4-408a20f58f7c.png)

Maybe something like this? But we lose type-safety. 

------------------

After some thought, a class level grid decorator may be better..

![image](https://user-images.githubusercontent.com/26264925/106592686-ace69800-6504-11eb-8404-11a65154d7db.png)

This way we have access to nested keys

**Comment by aburtsev** [comment]
![image](https://user-images.githubusercontent.com/3891411/106613861-b9f29e00-657b-11eb-84de-c0939f987fc3.png)
