### ISSUE TITLE
Implement cascade delete

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#567]
Is there other way to do this in prisma natively?

https://www.prisma.io/docs/guides/general-guides/database-workflows/cascading-deletes/postgresql

**Comment by artonio** [comment]
As far as my research goes, we cannot annotate it in schema.prisma or with a decorator like in TypeORM, CASCADE DELETE is a DB feature and according to the docs we need to write SQL statements to alter our tables with cascade delete. There are however two alternative solutions that i can think of. 

1. We can manually delete whatever we need to as part of the same query using nested delete: {}
2. We can use a community library: https://paljs.com/plugins/delete
3. We follow prisma docs and alter our db to delete on cascade

**Comment by webberwang** [comment]
- [ ] Lets implement method #2 first

For delete app you'll see that we manually delete pages. 

- [ ] For delete app spec, add 1 extra page. (should have 2 at this point, initial create app adds a default page). Find all page id's, then assert delete they should be gone.
