### ISSUE TITLE
Sketch mockup

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#600]
We'll want to do a high fidelity mockup to use in our landing page, as well as giving us a final design to work towards.

Use this as inspiration 

- https://uibakery.io/ 

https://www.icloud.com/iclouddrive/0U1DZu8AuNujCcr716qYqQWeQ#Codelab_Demo

We will ignore the home page, & the apps page (even though it is shown in the demo video).

The page we'll build is the builder page with the left sidebar navigation. This UI took inspiration from https://webflow.com/ (please create an account and try out their UI)

The builder layout is accessible when we click on a specific app from the app page. The default view we'll see is this.

![image](https://user-images.githubusercontent.com/26264925/107853497-4d716d80-6dcb-11eb-9a4c-ccce513f3272.png)

The 4 menu option on the left is 

- Apps - goes back to apps list
- Pages - shows the list of pages the app has, and we can click a page to show its content
- Components - A list of components that we can drag and drop onto the page
- Tree - A tree view of our application (can see in webflow.com)

Clicking on the left sidebar can bring up a Main panel, then clicking on a list item in the Main panel could bring up an additional Detail panel.

The right sidebar is always open (inspired by webflow). Right now we have 2 tabs. Props & Style.

Props you can think of as Component specific configurations.  You can find the fields for each props here https://ant.design/components/button/

For each component you can go to the `api` section and see which field names are available, and also which input type it is. 

The Style tab would be the same for all components, think of this like CSS in general.

We also want a UI to create a Style, and a Style can be assigned to any Component on the page. A style is simply any combination of CSS rules. 

![image](https://user-images.githubusercontent.com/26264925/107853670-25363e80-6dcc-11eb-9a9a-20f247826d7a.png)

We could look at theirs.

----------

Also some places we may use widgets or some sections to display in the landing page, while others we would show the full page.

**Comment by AntonZii** [comment]
Here is the first variant of the design
![1](https://user-images.githubusercontent.com/79014676/107946210-60d23380-6f99-11eb-9061-56537a9ed8b3.png)
![2](https://user-images.githubusercontent.com/79014676/107946215-62036080-6f99-11eb-85ca-3d275cfb2737.png)

**Comment by AntonZii** [comment]
components/tree
![Components](https://user-images.githubusercontent.com/79014676/108091646-96078000-7084-11eb-9415-8386462f213e.png)
![Tree 1](https://user-images.githubusercontent.com/79014676/108091655-97d14380-7084-11eb-82bb-573aac1f57be.png)
![Tree 2](https://user-images.githubusercontent.com/79014676/108091659-9869da00-7084-11eb-9e5a-74573cfb9109.png)
