### ISSUE TITLE
Hasura Postgresql Research

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#679]
Why are there so many tables? 
![image](https://user-images.githubusercontent.com/26264925/112587893-ab767500-8dbb-11eb-899a-5b5afb86bc50.png)

How do we run an sql in something like pgadmin4?

**Comment by artonio** [comment]
I do not see the same thing with Webstorm, here are my settings

![aws_webstorm_connection_settings](https://user-images.githubusercontent.com/7527357/112698179-80ddf800-8e5f-11eb-96fd-2deef31d5a24.png)
![run_sql_in_webstorm](https://user-images.githubusercontent.com/7527357/112698188-84717f00-8e5f-11eb-85d5-c3df858c0122.png)
![webstorm_aws_db](https://user-images.githubusercontent.com/7527357/112698189-84717f00-8e5f-11eb-8ee5-9e4c6b2a7058.png)

**Comment by webberwang** [comment]
Pretty curious what those extra tables are, is that how it's supposed to be? does it degrade db performance?
