### ISSUE TITLE
Assign app to user

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#681]
Using jwt user id from claim in hasura, maybe auth0 related

the form would not pass userId

https://hasura.io/docs/latest/graphql/core/auth/authentication/jwt.html

**Comment by artonio** [comment]
Things that were done:

1. Update Hasura Claims rule at Auth0 dashboard to:
```function (user, context, callback) {
  const namespace = "https://hasura.io/jwt/claims";
  context.idToken[namespace] =
    {
      'x-hasura-default-role': 'user',
      // do some custom logic to decide allowed roles
      'x-hasura-allowed-roles': ['user'],
      'x-hasura-user-id': user.user_id
    };
  callback(null, user, context);
}
```

2. Updated permissions for user role for table app and pages (if we keep it as 'user' role we need to apply it to all tables, let me know if 'user' is a good role name or you would like something else)

![Screenshot from 2021-03-29 23-08-43](https://user-images.githubusercontent.com/7527357/112928082-0540ad00-90e4-11eb-925c-201147001fc1.png)

Now user_id is not required and will be filled automatically from the session variable
