### ISSUE TITLE
Add slider component

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#7]
__Source:
Migrate the slider component in `@codelab/ui` package of repository https://bitbucket.org/codelabstudios/codelab using branch `develop`.

Do not run or compile the bitbucket repository, just look at the code and manually migrate over.

__Destination:
Fork this repository & migrate into the ui package of this repository then create PR. Check readme for full details.

Read this https://github.com/codelab-ai/codelab.ai/issues/1 but only do Slider

**Comment by Super117** [comment]
Okay, I will do.
