### ISSUE TITLE
Component builder

### ISSUE THREAD

**Issue by antonmihaylov** [codelab-ai/codelab.ai#757]
Following #753  and #752, we need a way to create components and their elements.

Both Page Builder and Component builder are essentially tree builders. And we already have the abstraction for them - Cytoscape.

- [x] Add and implement fromComponent to CytoscapeService which takes a Component and returns a generic Cytoscape graph
- [x] Add a "Component builder" left pane where components can be created, modified, and deleted
- [x] Add an Antd tree, similar to our Page tree, inside the Component builder. We display all component elements In the tree
- [x] Ability to insert component elements in the tree using the right pane, like Vertices in v0.0.4 
- [ ] Props form in the right pane (ON HOLD - once we fix the props form #661)
- [X] Unit tests for builder

**Comment by webberwang** [comment]
I’m thinking a right drawer that pops up whenever we click on a node in the tree
