### ISSUE TITLE
Cypress tests authentication

### ISSUE THREAD

**Issue by antonmihaylov** [codelab-ai/codelab.ai#777]
Ideally, we would log in using the Password grant, with an API call, like this:
 https://auth0.com/blog/end-to-end-testing-with-cypress-and-auth0/
 
But we use nextjs-auth0 to manage our authentication process. And it encrypts the cookies and doesn't expose the encryption process. Meaning that even if we did make the login request and got the token, we can't easily store it in our cookie, since we don't have access to how it stores it.
  
I see the following options:
- Login using the UI in cypress (current, but flaky)
- Perhaps use this library https://github.com/sir-dunxalot/cypress-nextjs-auth0 but there's a PR that needs to be merged
- Impersonate the user using its id. But doesn't work because we auto redirect to the login page if someone is not authenticated, and this happens in SSR, where we can't stub requests with cypress
- Intercept all requests to auth0 and mock them - can't do, because some of them happen in SSR
- Figure out how the nextjs-auth0 lib stores and encrypts the cookie and use the same method to store it

**Comment by webberwang** [comment]
I had in mind to just conditionally set the proxy with admin token if were in ci, but would seem odd to have this code in production

**Comment by antonmihaylov** [comment]
but we redirect automatically in SSR if the user is not authenticated, can't proxy that easily. Unless we turn off redirection, but that would be a bandaid

**Comment by webberwang** [comment]
ah right because of the auth0 hooks, logging in seems the best solution right now
