### ISSUE TITLE
Props module using DGraph

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#825]
https://lucid.app/lucidchart/001b9059-6d3e-47de-9712-691bde994df0/edit?page=0_0#

**Comment by aburtsev** [comment]
**Stage**: PropTypes

- [ ] facets vs PropTypeLink
- [ ] dgraph types for PropTypeLink
- [ ] getPropTypesList - Collections (shallow)
- [ ] getPropTypes - deep
- [ ] createPropTypesList
- [ ] updatePropTypesList
- [ ] deletePropTypesList
- [ ] recursive jsonschema for propType
- [ ] recursive query via `@custom`

**Comment by aburtsev** [comment]
Use PropTypeLink until [this thread](https://discuss.dgraph.io/t/facets-in-graphql/10429) will not be resolved (native support for @facet). Currently, it's painful to use facets with graphql

**Comment by webberwang** [comment]
> Use PropTypeLink until [this thread](https://discuss.dgraph.io/t/facets-in-graphql/10429) will not be resolved (native support for @facet). Currently, it's painful to use facets with graphql

I’ve diagramed without the need for facets, each node will be a field

**Comment by aburtsev** [comment]
[Here](https://discuss.dgraph.io/t/how-to-use-facets-with-slash/9652/7) described that @custom can be used only for query facets, not for mutation

Also in this thread mentioned that [Lambda](https://dgraph.io/docs/master/graphql/lambda/overview/) can be used for this. But they haven't released yet

**Comment by aburtsev** [comment]
Also, I tried to add PropTypesLinks, but it appears that recurse can be used only on one level.
I mean there is no way to have following recursion `PropType->PropTypeLink->PropType->PropTypeLink...`
So currently it looks like we have 2 options:
1. Use DQL for `Prop` and `PropTypes`. The drawback is that it'll not be consistent with others
2. Use simple `PropType->PropType->PropType->...`. i.e. `key` will be a part of `PropType` itself. The drawback is that it'll be impossible to rename `PropType` while reusing 

I propose to go 2nd way. The dgraph team already works on facets integration, when they add this feature we can easily improve our workflow to just add facets. But the main question is when they do this.
@webberwang  what do you think?

**Comment by webberwang** [comment]
@aburtsev Our new UI means we wouldn't need this requirement. We'll only link at most 1 level
