### ISSUE TITLE
Setup Cypress e2e for CircleCI

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#836]
Search config for `e2e` in `config.yml`, it's currently commented out.

Do run cypress locally, `yarn`, `yarn build`, then `make e2e-dev`. This starts new ports for web & api.

> Normally these are called `nx run web`, `nx run api`, which runs on different ports. We use different ports so no conflict

**Comment by svitalii33** [comment]
> Search config for `e2e` in `config.yml`, it's currently commented out.
> 
> Do run cypress locally, `yarn`, `yarn build`, then `make e2e-dev`. This starts new ports for web & api.
> 
> > Normally these are called `nx run web`, `nx run api`, which runs on different ports. We use different ports so no conflict

I noticed that cypress/run job works okay in the pipeline.
