### ISSUE TITLE
IsAppOwnerAuthGuard discussion

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#859]
Why not use a custom grapqhl query with `@custom` directive, to create a query that let's us query only app belong to the current user?

The issue we had was auth for gql, now that we took care of auth with our own graphql layer, we could safely access gql

Having a decorator for each kind of foreign constraint could mean too many decorators, I think it should be moved to the gql layer

**Comment by antonmihaylov** [comment]
The IsAppOwnerAuthGuard is not for querying apps, it's for updating and deleting apps. It prevents users to update and delete an app, unless they are the owner

**Comment by webberwang** [comment]
Okay I see now thanks
