### ISSUE TITLE
Dgraph Graphql Discussion

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#860]
The reason we don’t call dgraph graphql api directly in frontend is because we can’t selectively hide queries/mutations and would have to expose all at once?

Or was it to do with the auth? 

(Aside from the part about the mutation where the user can assign to another user’s id)

**Comment by antonmihaylov** [comment]
The main reason was that we can't enforce authorization in custom dql queries, so we need to put a layer on top of it and somehow protect our /mutate /query endpoints (with reverse proxy configuration). Also, dgraph's authorization is lacking some features, like post-update hooks

The secondary reason was that we can hide our DB schema from our frontend and present it with only what it needs to see - for example - process the component tree in the backend and present a simple representation to the frontend. And to  handle the logic in there basically

The third reason was to have a unifying API (in the face of our nest graphql API)

https://github.com/codelab-ai/codelab.ai/issues/834#issuecomment-840736483
