### ISSUE TITLE
Storybook for "Node" package is broken

### ISSUE THREAD

**Issue by aburtsev** [codelab-ai/codelab.ai#88]
## Current Behavior
Storybook for "Node" workspace doesn't start

## Expected Behavior
Storybook for "Node" package should run as expected 

## Steps to Reproduce
1. Run "nx storybook node".
2. Runner generates the error (see screenshot below) 

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
1. ![image](https://user-images.githubusercontent.com/3891411/92734045-ddc10780-f380-11ea-86d7-f83e14d7bb95.png)

### Solution
![image](https://user-images.githubusercontent.com/3891411/92735181-dea66900-f381-11ea-8196-ed118cec3396.png)

@webberwang

**Comment by webberwang** [comment]
The node package was generated recently, the default generated storybook config uses `./lib`, must have not used it yet, thanks for reporting this
