### ISSUE TITLE
page-api specs

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#885]
Checkout `nx test modules-app-api --runInBand`

For integration specs we'll want to use runInBand for non-parallel mode.

**Comment by angelwong0963** [comment]
via Hubstaff
User: Angel Wong

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/03/21 - 07/10/21
Work session total: 28:06:46
Billable: Yes

Grand total: 28:06:46
