### ISSUE TITLE
Make storybook suffixes consistent through project

### ISSUE THREAD

**Issue by aburtsev** [codelab-ai/codelab.ai#89]
@webberwang 
## Description
It's about file naming convention. Currently, storybook files have two kinds of suffixes: ".stories" and ".story". I suggest using only one suffix for purpose of consistency. I think a better choice will be ".stories", because: 
1. already almost every story-file has such kind of suffix
2. it'll give us the ability to have one and more stories in the same file (because if we'll use 'story' it restricts us to only one story)
3. Current configs assume that stories ending with ".stories"

Below screenshot with the list of "story"-ending files

![image](https://user-images.githubusercontent.com/3891411/92736610-1b269480-f383-11ea-8d5c-48e73c36e8f1.png)

**Comment by webberwang** [comment]
thanks for catching this I'll update them to `*.stories.tsx`
