### ISSUE TITLE
Make integration tests pass on ci

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#896]
Since integration has been fixed locally, we'll want to make it pass on CI.

There has been some build error in the latest build on CI, could be related to env?

**Comment by webberwang** [comment]
@svitalii33 this now passes locally with `yarn test --runInBand` relates to https://github.com/codelab-ai/codelab.ai/issues/901

#901 would simplify the build tool a bit, but not a requirement

**Comment by svitalii33** [comment]
via Hubstaff
User: vitalii

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/06/21 - 07/07/21
Work session total: 6:43:52
Billable: Yes

Grand total: 6:43:52
