### ISSUE TITLE
Export types from all ui components

### ISSUE THREAD

**Issue by aburtsev** [codelab-ai/codelab.ai#90]
@webberwang 
## Description
Currently "ui" package export types only for the following components: "button" and "text". It'll be convenient to export types for all components. It'll give IDE the ability to understand code better.
As an example when you try to work with tree IDE suggests types from antD, but that's not the right types. Right types located near the component.

**Comment by webberwang** [comment]
Thanks I'll make a PR for this

**Comment by webberwang** [comment]
<img width="1443" alt="List_types_ts_—_codelab__Workspace_" src="https://user-images.githubusercontent.com/26264925/92821585-13192580-f380-11ea-9360-bea48311a8f9.png">

**Comment by webberwang** [comment]
Fixed by #93

**Comment by VienNguyen24hdev** [comment]
via Hubstaff
User: Nguyen Luong Vien

Project: Codelab - https://app.hubstaff.com/projects/1093588
Date Range: 09/10/20 - 09/11/20
Work session total: 5:44:15
Billable: Yes

Grand total: 5:44:15
