### ISSUE TITLE
Vault CircleCI Integration

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#917]
I'm practicing making videos in preparation for youtube tutorials of our software product, I think these are better than written text at describing things

Use branch `0-vault`

https://www.youtube.com/watch?v=3LMCl8a1dk8

**Comment by svitalii33** [comment]
via Hubstaff
User: vitalii

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/07/21 - 07/10/21
Work session total: 8:00:27
Billable: Yes

Grand total: 8:00:27
