### ISSUE TITLE
Misc fixes

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#923]
- [X] Remove `*Validation` schema from `dgraph/schema.graphql`, to new developers they may not know it's not used currently
- [X] Rename `Props` to `API` for the components
- [X] Rename to `adapter` spelling
- [X] ~~Reduce~~ map better here? https://github.com/codelab-ai/codelab.ai/blob/17175be8c112bebf9b5a63194723ac727eaf3e0d/libs/modules/type/src/interfaceForm/JsonModelUpsertPropsAdaptor.ts#L59-L86
- [X] Use generated type? https://github.com/codelab-ai/codelab.ai/blob/17175be8c112bebf9b5a63194723ac727eaf3e0d/libs/modules/type/src/interfaceForm/JsonModelUpsertPropsAdaptor.ts#L111
- [X] Remove/comment out the Validators, if you think it may be beneficial in future we can have it commented.

**Comment by antonmihaylov** [comment]
via Hubstaff
User: Anton Mihaylov

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/08/21 - 07/08/21
Work session total: 0:00:02
Billable: Yes

Grand total: 0:00:02
