### ISSUE TITLE
Consider using a Dgraph ORM

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#925]
What are the pros/cons have using a third party lib for the Dgraph layer?

Something like this,

https://avishwakarma.github.io/dgraph-orm/#/

We could fork & expand on it

**Comment by antonmihaylov** [comment]
![image](https://user-images.githubusercontent.com/57956282/124961698-75859580-e026-11eb-9414-fab4892312fb.png)

**Comment by antonmihaylov** [comment]
via Hubstaff
User: Anton Mihaylov

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/08/21 - 07/09/21
Work session total: 0:22:56
Billable: Yes

Grand total: 0:22:56
