### ISSUE TITLE
Setup staging for vercel

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#931]
We'll want `https://staging.codelab.ai` (vercel) to access `https://api.staging.codelab.ai` (aws setup)

**Comment by webberwang** [comment]
Fixed by #938 938

**Comment by svitalii33** [comment]
via Hubstaff
User: vitalii

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/10/21 - 07/10/21
Work session total: 6:00:19
Billable: Yes

Grand total: 6:00:19
