### ISSUE TITLE
Test out AWS Apprunner with Dgraph

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#939]
Let's move our CI Dgraph from cloud to using Apprunner with docker. This will give us a chance to see what limitations it has, and what benefits we can get from that.

**Comment by svitalii33** [comment]
via Hubstaff
User: vitalii

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/13/21 - 07/21/21
Work session total: 4:35:52
Billable: Yes

Grand total: 4:35:52
