### ISSUE TITLE
Add enum for Node React types

### ISSUE THREAD

**Issue by aburtsev** [codelab-ai/codelab.ai#94]
@webberwang 
## Description
In ReactNodeI we have field "type". Currently, its type is "string', but not every string is valid "type". So I suggest specifying an enum and type for React Node "type". 

## Suggested Implementation

`
export enum NodeReactTypeEnum {
  'React.Fragment' = 'React.Fragment',
  'Html.div' = 'Html.div',
  'Html.p' = 'Html.p',
  'Html.a' = 'Html.a',
  'Html.span' = 'Html.span',
  'Text' = 'Text',
  'Icon' = 'Icon',
  'Menu' = 'Menu',
  'Menu.Item' = 'Menu.Item',
  'Menu.ItemGroup' = 'Menu.ItemGroup',
  'Menu.SubMenu' = 'Menu.SubMenu',
  'Card' = 'Card',
  'Card.Grid' = 'Card.Grid',
  'Card.Meta' = 'Card.Meta',
  'Typography' = 'Typography',
  'Typography.Title' = 'Typography.Title',
  'Typography.Text' = 'Typography.Text',
  'Typography.Paragraph' = 'Typography.Paragraph',
  'Alert' = 'Alert',
  'Affix' = 'Affix',
  'AutoComplete' = 'AutoComplete',
  'Button' = 'Button',
  'Breadcrumb' = 'Breadcrumb',
  'Breadcrumb.Item' = 'Breadcrumb.Item',
  'Dropdown' = 'Dropdown',
  'Form' = 'Form',
  'Form.Item' = 'Form.Item',
  'Form.List' = 'Form.List',
  'Checkbox' = 'Checkbox',
  'Input' = 'Input',
  'InputNumber' = 'InputNumber',
  'Select' = 'Select',
  'Select.Option' = 'Select.Option',
  'Grid' = 'Grid',
  'ResponsiveGrid' = 'ResponsiveGrid',
  'Provider' = 'Provider',
  'Modal' = 'Modal',
  'Radio.Group' = 'Radio.Group',
  'Radio' = 'Radio',
  'Rate' = 'Rate',
  'Slider' = 'Slider',
  'Switch' = 'Switch',
  'Space' = 'Space',
  'DatePicker' = 'DatePicker',
  'Divider' = 'Divider',
  'Pagination' = 'Pagination',
  'PageHeader' = 'PageHeader',
  'Badge' = 'Badge',
  'Avatar' = 'Avatar',
  'Comment' = 'Comment',
  'Calendar' = 'Calendar',
  'Descriptions' = 'Descriptions',
  'Descriptions.Item' = 'Descriptions.Item',
  'Empty' = 'Empty',
  'Timeline' = 'Timeline',
  'Timeline.Item' = 'Timeline.Item',
  'Tabs' = 'Tabs',
  'Tabs.TabPane' = 'Tabs.TabPane',
  'Statistic' = 'Statistic',
  'Tooltip' = 'Tooltip',
  'Tag' = 'Tag',
  'Tree' = 'Tree',
  'Drawer' = 'Drawer',
  'Progress' = 'Progress',
  'Result' = 'Result',
  'Spin' = 'Spin',
  'Skeleton' = 'Skeleton',
  'Anchor' = 'Anchor',
  'Anchor.Link' = 'Anchor.Link',
  'BackTop' = 'BackTop',
  'ConfigProvider' = 'ConfigProvider',
  'Popconfirm' = 'Popconfirm',
  'Transfer' = 'Transfer',
  'TreeSelect' = 'TreeSelect',
  'TreeNode' = 'TreeNode',
  'TimePicker' = 'TimePicker',
  'Upload' = 'Upload',
  'Steps' = 'Steps',
  'Steps.Step' = 'Steps.Step',
  'Collapse' = 'Collapse',
  'Collapse.Panel' = 'Collapse.Panel',
  'Carousel' = 'Carousel',
  'List' = 'List',
  'List.Item' = 'List.Item',
  'List.Item.Meta' = 'List.Item.Meta',
  'Mentions' = 'Mentions',
  'Mentions.Option' = 'Mentions.Option',
  'Layout' = 'Layout',
  'Layout.Header' = 'Layout.Header',
  'Layout.Sider' = 'Layout.Sider',
  'Layout.Content' = 'Layout.Content',
  'Layout.Footer' = 'Layout.Footer',
  'Cascader' = 'Cascader',
  'Popover' = 'Popover',
}

export type NodeReactType = 'React.Fragment' |
  'Html.div' |
  'Html.p' |
  'Html.a' |
  'Html.span' |
  'Text' |
  'Icon' |
  'Menu' |
  'Menu.Item' |
  'Menu.ItemGroup' |
  'Menu.SubMenu' |
  'Card' |
  'Card.Grid' |
  'Card.Meta' |
  'Typography' |
  'Typography.Title' |
  'Typography.Text' |
  'Typography.Paragraph' |
  'Alert' |
  'Affix' |
  'AutoComplete' |
  'Button' |
  'Breadcrumb' |
  'Breadcrumb.Item' |
  'Dropdown' |
  'Form' |
  'Form.Item' |
  'Form.List' |
  'Checkbox' |
  'Input' |
  'InputNumber' |
  'Select' |
  'Select.Option' |
  'Grid' |
  'ResponsiveGrid' |
  'Provider' |
  'Modal' |
  'Radio.Group' |
  'Radio' |
  'Rate' |
  'Slider' |
  'Switch' |
  'Space' |
  'DatePicker' |
  'Divider' |
  'Pagination' |
  'PageHeader' |
  'Badge' |
  'Avatar' |
  'Comment' |
  'Calendar' |
  'Descriptions' |
  'Descriptions.Item' |
  'Empty' |
  'Timeline' |
  'Timeline.Item' |
  'Tabs' |
  'Tabs.TabPane' |
  'Statistic' |
  'Tooltip' |
  'Tag' |
  'Tree' |
  'Drawer' |
  'Progress' |
  'Result' |
  'Spin' |
  'Skeleton' |
  'Anchor' |
  'Anchor.Link' |
  'BackTop' |
  'ConfigProvider' |
  'Popconfirm' |
  'Transfer' |
  'TreeSelect' |
  'TreeNode' |
  'TimePicker' |
  'Upload' |
  'Steps' |
  'Steps.Step' |
  'Collapse' |
  'Collapse.Panel' |
  'Carousel' |
  'List' |
  'List.Item' |
  'List.Item.Meta' |
  'Mentions' |
  'Mentions.Option' |
  'Layout' |
  'Layout.Header' |
  'Layout.Sider' |
  'Layout.Content' |
  'Layout.Footer' |
  'Cascader' |
  'Popover'; 
`

**Comment by webberwang** [comment]
This is great thanks, the union type is needed I agree. For enum not so much because we want to use string as opposed to variable when building our json data

**Comment by aburtsev** [comment]
Enums are more flexible. 
It can be used to get all possible values for some "Select" in out UI (I mean Object.values(someEnum).
Also, I finally remember a more elegant solution to generate types from enum:
export type NodeReactType = keyof typeof NodeReactTypeEnum;
 
So, we can have only enums and then easily convert them in any view

**Comment by webberwang** [comment]
@aburtsev Thanks for that, the `keyof typeof` does work great. I would use enums instead of union type in this case

**Comment by webberwang** [comment]
<img width="1435" alt="node-react_ts_—_codelab__Workspace_" src="https://user-images.githubusercontent.com/26264925/92981101-58575900-f44d-11ea-8c84-695906555a64.png">

**Comment by webberwang** [comment]
Fixed by #95

**Comment by aburtsev** [comment]
> <img alt="node-react_ts_—_codelab__Workspace_" width="1435" src="https://user-images.githubusercontent.com/26264925/92981101-58575900-f44d-11ea-8c84-695906555a64.png">
> 
> [microsoft/TypeScript#17690](https://github.com/microsoft/TypeScript/issues/17690)

Yes. Here only typecasting will work, but that isn't a great solution. But we at least can restrict it a little bit by using generated union type instead of just string.
