### ISSUE TITLE
Auth0 env

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#941]
We have dev, staging, prod environments overall. So each should be accompanied by their own Auth0 tenant.

`codelab-ai` Production label is the one we are using on development environment currently. So we'll want to use `codelab-ai-dev` instead.

`codelab-ai-staging` should be setup with staging, login currently doesn't work on `https://staging.codelab.ai`.

`codelab-ai` will be put on pause until production environment is ready.

---

Under each `Applications`, we have a Regular Web Application for the React client, and a Machine to Machine for e2e tests to fetch specs (this will soon be deprecated in favor of mocking).

**Comment by svitalii33** [comment]
via Hubstaff
User: vitalii

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/13/21 - 07/14/21
Work session total: 8:08:37
Billable: Yes

Grand total: 8:08:37

**Comment by svitalii33** [comment]
via Hubstaff
User: vitalii

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/15/21 - 07/15/21
Work session total: 0:03:09
Billable: Yes

Grand total: 8:11:46
