### ISSUE TITLE
Refactor to use dql instead of graphql

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#945]
Start with `*` ones

- [X] app-api
- [X] atom-api
- [X] element-api*
- [X] page-api
- ~[X] prop-api~
- [X] type-api
- [X] user-api - no dgraph here

Fix specs:
- [X] app-api specs
- [X] atom-api specs
- [X] element-api specs
- [X] page-api specs
- ~[ ] prop-api specs~
- [X] type-api specs

**Comment by antonmihaylov** [comment]
via Hubstaff
User: Anton Mihaylov

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/15/21 - 07/30/21
Work session total: 64:34:34
Billable: Yes

Grand total: 64:34:34

**Comment by antonmihaylov** [comment]
via Hubstaff
User: Anton Mihaylov

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/31/21 - 07/31/21
Work session total: 0:00:01
Billable: Yes

Grand total: 64:34:35
