### ISSUE TITLE
Deploy storybook

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#947]
<img width="868" alt="GitKraken" src="https://user-images.githubusercontent.com/26264925/125917092-9ef828da-7717-460d-be3a-bfbd9fc7ab2d.png">

This breaks `nx storybook web`

1. Add `nx build-storybook web` to our husky pipeline
2. Deploy the built storybook to vercel

**Comment by svitalii33** [comment]
via Hubstaff
User: vitalii

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/16/21 - 07/20/21
Work session total: 6:32:40
Billable: Yes

Grand total: 6:32:40

**Comment by svitalii33** [comment]
via Hubstaff
User: vitalii

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/21/21 - 07/21/21
Work session total: 0:02:02
Billable: Yes

Grand total: 6:34:42
