### ISSUE TITLE
Standalone domain

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#954]
We can build an app along with pages using our platform, but I haven't thought about how we could allow users to use their own domain name to serve the app.

For example, if I'm building a landing page for my personal portfolio using `https://codelab.ai`, how could I link my own domain `https://webberwang.com` to the page on the platform

The format would be `https://codelab.ai/[username]/[app_name]/[page_name]`

So `https://webberwang.com` should display the content on `https://codelab.ai/webber/portfolio/home`.

Is this a simple DNS config for `https://webberwang.com`?

---

Here's a demo on our current features https://www.youtube.com/watch?v=-ifBs8IAR7M, in case you are wondering what the product does exactly

**Comment by svitalii33** [comment]
> We can build an app along with pages using our platform, but I haven't thought about how we could allow users to use their own domain name to serve the app.
> 
> For example, if I'm building a landing page for my personal portfolio using `https://codelab.ai`, how could I link my own domain `https://webberwang.com` to the page on the platform
> 
> The format would be `https://codelab.ai/[username]/[app_name]/[page_name]`
> 
> So `https://webberwang.com` should display the content on `https://codelab.ai/webber/portfolio/home`.
> 
> Is this a simple DNS config for `https://webberwang.com`?
> 
> Here's a demo on our current features https://www.youtube.com/watch?v=-ifBs8IAR7M, in case you are wondering what the product does exactly

**Comment by svitalii33** [comment]
via Hubstaff
User: vitalii

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/28/21 - 09/10/21
Work session total: 22:30:24
Billable: Yes

Grand total: 22:30:24
