### ISSUE TITLE
Vercel build error

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#964]
https://vercel.com/codelabai/codelab/C7Zvb6eAyZByTuUSLYhQBq8EZKu6

**Comment by svitalii33** [comment]
via Hubstaff
User: vitalii

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/23/21 - 07/23/21
Work session total: 2:34:41
Billable: Yes

Grand total: 2:34:41
