### ISSUE TITLE
Separate devops repo

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#975]
- Extract all devOps related code, terraform, aws config files etc
- Remove all un-used devOps files, like EBS code, vault etc

I'm guessing Circleci needs to stay in main repo, and everything else can go to https://github.com/codelab-ai/codelab.ai-infrastructure?

- Docker files would be split between both repos, some development setup are still needed in main. While building docker files would be in infrastructure repo only

**Comment by svitalii33** [comment]
via Hubstaff
User: vitalii

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/26/21 - 07/27/21
Work session total: 7:37:18
Billable: Yes

Grand total: 7:37:18
