### ISSUE TITLE
Txn cleanup

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#988]
Instead of cleaning up tx after excuteMutation, is it possible to clean up after executeTransaction has been called?

<img width="506" alt="update-lambda_service_ts_—_codelab" src="https://user-images.githubusercontent.com/26264925/127728882-45ffc7ab-dc01-431d-94d6-271991db772c.png">

**Comment by antonmihaylov** [comment]
Do you mean to commit or to dispose

**Comment by antonmihaylov** [comment]
We could commit it in DqlUseCase, in a then block. That way it will get committed if we don't throw.

But this isn't used a lot since I made all other mutations void or returning just the id in case of create use cases. I.e they only need one txn

**Comment by antonmihaylov** [comment]
Will we ever need to commit a mutation manually?
